// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATMx5eR1YpC0qF8Kf6OQalBgoVf05-PRs',
    appId: '1:1002942112869:web:121a20f4b9ddc466e7128c',
    messagingSenderId: '1002942112869',
    projectId: 'shukare-firebase',
    authDomain: 'shukare-firebase.firebaseapp.com',
    storageBucket: 'shukare-firebase.firebasestorage.app',
    measurementId: 'G-EHJGRL5WSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBreetDZvax2eat0pHgxDOd8Oh9el9qpSg',
    appId: '1:1002942112869:android:f9044e7edf7cec18e7128c',
    messagingSenderId: '1002942112869',
    projectId: 'shukare-firebase',
    storageBucket: 'shukare-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOqTTBmU9Iv2A6gmEvaFPSaegO6S8OD8Q',
    appId: '1:1002942112869:ios:d194037eaf32ad6be7128c',
    messagingSenderId: '1002942112869',
    projectId: 'shukare-firebase',
    storageBucket: 'shukare-firebase.firebasestorage.app',
    iosBundleId: 'com.example.shukare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOqTTBmU9Iv2A6gmEvaFPSaegO6S8OD8Q',
    appId: '1:1002942112869:ios:0325421bb98c76c7e7128c',
    messagingSenderId: '1002942112869',
    projectId: 'shukare-firebase',
    storageBucket: 'shukare-firebase.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATMx5eR1YpC0qF8Kf6OQalBgoVf05-PRs',
    appId: '1:1002942112869:web:214694023ccbbb9ae7128c',
    messagingSenderId: '1002942112869',
    projectId: 'shukare-firebase',
    authDomain: 'shukare-firebase.firebaseapp.com',
    storageBucket: 'shukare-firebase.firebasestorage.app',
    measurementId: 'G-K38N0VVK8X',
  );
}
